### ISSUE TITLE
How to visualize the game

### ISSUE THREAD

**Issue by leixy20** [alfworld/alfworld#36]
Thanks for your great work!
I wonder if there are some methods to visualize the game and produce a video like your awesome demo in the project page. Thanks!

**Comment by MohitShridhar** [comment]
@leixy20 

It's been a while since I worked on ALFWorld, so I don't remember exactly how I did it. But I think I saved a sequence of actions, then used [augment_trajectories.py](https://github.com/alfworld/alfworld/blob/master/scripts/augment_trajectories.py) to replay the actions and save PNGs with smooth_actions=True. These PNGs were stitched into a video with mmpeg encoder.

**Comment by MarcCote** [comment]
@leixy20 did you manage to produce a video to your liking?

**Comment by leixy20** [comment]
Thanks for your guidance. However, I've been a little busy recently, and I'll let you know when I produce my video.
Best wishes.

**Comment by MarcCote** [comment]
Closing for now. Please re-open if needed.
