### ISSUE TITLE
Bug:lacking of a comma symbol in a list

### ISSUE THREAD

**Issue by kanxueli** [alfworld/alfworld#37]
This line https://github.com/alfworld/alfworld/blob/master/alfworld/gen/constants.py#L342C8-L342C8. is missing a comma, which will cause an error when the code indexes the objects in this list.

**Comment by MarcCote** [comment]
Thanks for the catch.

Did you actually got an `IndexError`? Quickly looking at the code, it seems this list is only used to determine the prior distribution of where we can typically find a given object, i.e. to build `OBJECT_TO_VAL_RECEPTACLE`. As far as I can see, this is only used in the handcoded expert to simulate a pseudo-guided search (e.g. we use commonsense knowledge to find suitable location(s) for a given object). If the objects is not in that 

So, because "sidetable" and "teddybear" will be concatenated, the search for a suitable location will default to a brute-force search, here: https://github.com/alfworld/alfworld/blob/master/alfworld/agents/expert/handcoded_expert.py#L234-L235
