### ISSUE TITLE
TextWorld license

### ISSUE THREAD

**Issue by chkla** [alfworld/alfworld#48]
Hi everyone, I was wondering if the TextWorld license has changed? You state that it is licensed under the GNU General Public License (GPL) v2.0 License. But in the original repository, it is licensed under the MIT License https://github.com/microsoft/TextWorld/blob/main/LICENSE.txt.

Best
Christopher

**Comment by MarcCote** [comment]
TextWorld's code is still released under the MIT License but I should provide some clarifications in its README. TextWorld supports loading different game formats, each requiring a specific engine/parser with its own license. For instance, to load the classic Z-Machine format (`.z8`), TextWorld uses [Jericho](https://github.com/microsoft/jericho) which is under GPL 2.0. In the case of ALFWorld, we want to load `.tw-pddl` which uses a custom fork of [Fast-Downward](https://github.com/MarcCote/downward) (under GPL 3.0).

Since we are not loading `.z8` games for ALFWorld, I think the ALFWorld's README should say
> TextWorld - MIT License

instead of 

> TextWorld (Jericho) - GNU General Public License (GPL) v2.0

I hope this answers your question?

**Comment by chkla** [comment]
Hi Marc, many thanks for your super quick response and for providing clarification. Now it is much clearer and definitely answered my question. Thanks again and have a great week, Christopher
