### ISSUE TITLE
QAs 

### ISSUE THREAD

**Issue by zhaozj89** [alfworld/alfworld#5]
Thanks for this work again. I have a couple of questions when digesting the code and paper.

1. What is `CQAttention` network (`agents/modules/layers.py`) that is used to aggregate input information? Can you point me to the paper?

2. To replicate the BUTLER::BRAIN experiment results, should I just run `python dagger/train_dagger.py config/base_config.yaml`, i.e., using the default seq2seq action generator?

Thanks for your time.

**Comment by xingdi-eric-yuan** [comment]
Hi @zhaozj89 , 
1. The CQAttention is adopted from the QANet ([Yu et al., 2018](https://arxiv.org/abs/1804.09541)).
2. Yes I believe that's the right thing to do. @MohitShridhar please confirm.

Please let us know if you have any other questions.

**Comment by MohitShridhar** [comment]
Hi @zhaozj89 
1.  Also see Appendix A.3 in the paper for more details.
2. Yes, this is correct. The default settings should train a BUTLER::Brain agent on All Tasks.

**Comment by zhaozj89** [comment]
Thank you both, and sorry for my carelessness.

**Comment by zhaozj89** [comment]
@MohitShridhar , this is the result when I ran `python dagger/train_dagger.py config/base_config.yaml`. Is this the result expected? Why the games points of id, ood, and student are still 0s and the game steps of id, ood, and student are still 50s? I enclosed the`base_config.yaml` file (change `.yaml` to `.txt` because github does not support attaching `.yaml`) where I turn `run_eval` to `True` and `visdom` to `True`. Thanks.

<img width="1150" alt="Screenshot 2020-11-21 at 3 52 41 PM" src="https://user-images.githubusercontent.com/34164876/99870996-2e22d400-2c12-11eb-8ae0-2b208032d9aa.png">

[base_config.txt](https://github.com/alfworld/alfworld/files/5577214/base_config.txt)

**Comment by MohitShridhar** [comment]
@zhaozj89, no this is strange. Are you sure your txtfile parameters are being loaded correctly? Can you double check that it's saving dicts exactly like the YAML loader?

**Comment by xingdi-eric-yuan** [comment]
Yeah this definitely looks weird. Some observations: 1) at the very beginning, the game points is ~1.0, which means at the beginning the games are solvable and thus the oracle might be fine? 2) the loss is going all the way up.

I've never seen this during my hundreds of experiments of dagger training. @zhaozj89 can you try doing the same thing, but change the env.task_types to be [1] in the yaml? So that it will only train and test on the Pick&Place task type. Let's see if the easy setting can reproduce this. 

48 hours of training sounds normal to me.

**Comment by zhaozj89** [comment]
Thanks @xingdi-eric-yuan @MohitShridhar It turns out to be my fault that I modified `base_agent.py` code to add a comparison method but forgot to use the original opitmizer of dagger when training dagger. It is fine now. Sorry for my silly question and thanks a lot for your patience.

**Comment by zhaozj89** [comment]
Hi, I would like to inquire some questions on data generation.

I was following https://github.com/alfworld/alfworld/tree/master/alfworld/gen to generate new trajectories by executing 

`python scripts/generate_trajectories.py --save_path data/new_trajs --in_parallel --debug --num_threads 2`

But after hours running, I found that the following created folders were all empty:

<img width="1193" alt="Screenshot 2021-02-06 at 2 05 50 PM" src="https://user-images.githubusercontent.com/34164876/107110658-a6e61380-6884-11eb-944c-52eb344b8bca.png">

And the terminal continuously raised the value error `Empty plan is successful, no work to do`

<img width="1046" alt="Screenshot 2021-02-06 at 2 08 37 PM" src="https://user-images.githubusercontent.com/34164876/107110669-d432c180-6884-11eb-8f1e-0d331668048c.png">

Is this expected? I was trying to follow the execution step by step, but could not find where goes wrong. I want to use the PDDL method to design some real robot tasks, so I would to like investigate it more. Thanks.

By the way, I found a tiny bug here:

https://github.com/alfworld/alfworld/blob/master/alfworld/gen/scripts/generate_trajectories.py#L15

`import alfworld.gen.constants` should be `import alfworld.gen.constants as constants`

**Comment by MohitShridhar** [comment]
@zhaozj89 these generation scripts are from [ALFRED](https://github.com/askforalfred/alfred/tree/master/gen), which were used during data collection for the ALFRED dataset. For ALFWorld, we did not generate additional trajectories, and simply reused the existing ones from ALFRED. Are you trying to generate additional tasks for the dataset?

The failures `Empty plan is successful, no work to do` are probably due to discrepancies between the [original PDDL domain for ALFRED](https://github.com/askforalfred/alfred/blob/master/gen/planner/domains/PutTaskExtended_domain.pddl) and the [modified PDDL domain used in ALFWorld](https://github.com/alfworld/alfworld/blob/master/alfworld/data/alfred.pddl) to construct TextWorld games. Plus the simplified [PDDL goals in ALFWorld ](https://github.com/alfworld/alfworld/blob/master/alfworld/gen/goal_library.py) vs. [ALFRED Goals](https://github.com/askforalfred/alfred/blob/master/gen/goal_library.py). So if you replace the these two files – `alfred.pddl` and `goal_library.py` with originals from ALFRED, you should get more successful trajectories with the generation script.

**Comment by zhaozj89** [comment]
@MohitShridhar Thanks! I will have a look at ALFRED. 

Yes. I want to generate additional tasks for the dataset. I am interested in deploying an ALFWorld text agent on a real robot, such as NAO or PyRobot. I think the current task types `clean/heat/cool/pick two & place` seem to be a bit complicated for a real robot. I want to design some tasks that can interact with humans and are also easy to implement with NAO or PyRobot APIs. If you have any comments on this, please let me know. Thanks.

**Comment by MohitShridhar** [comment]
@zhaozj89 that sounds cool! Yeah, I would say Pick & Place is probably the easiest task for a real-robot setup. You need a robust manipulation pipeline that can pick-up objects based on segmentation masks, and a navigation pipeline that can execute high-level navigation commands like "go to the fridge". These are non-trivial components, but if you get some minimal setup working, you might be able to train agents directly with real-world data.
