### ISSUE TITLE
How to expand ALFWORLD to new Instruction datasets?

### ISSUE THREAD

**Issue by shengyin1224** [alfworld/alfworld#80]
Hi, authors! thanks for your great work!

ALFWORLD provides a way for many embodied agents to train in text-level. And in recent, I want to create new instruction dataset different from ALFRED but using the same scene setting. And I want to know if the instruction changes, can the ALFWORLD still provide the text description of the world? 

If ALFWORLD can not provide the text description of world, can I have a way to achieve the similar effect like ALFWORLD?

Thanks so much if you can take time to reply!

**Comment by xingdi-eric-yuan** [comment]
Hello, thanks for reaching out. Which dataset do you want to adapt ALFWorld to? If you have access to a smililar set of meta-information as we have in ALFRED (for example, PDDL that describes the world dynamics like [this](https://github.com/alfworld/alfworld/blob/master/alfworld/data/alfred.pddl)), then in principle you should be able to adapt our code to create a "text version" of your dataset. By "adapt" I mean you may have to re-implement many things using our code as a reference.

**Comment by shengyin1224** [comment]
Thanks for your reply! 
Actually, the dataset is created by ourself and it includes some actions unmentioned in ALFRED like 'break' or 'dirty' but supported by AI2THOR v5.0. I want to know if these changes make the adaptation of ALFWORLD difficult to achieve.

And I also know if there is a way to only use visual environment AI2THOR provides and turn it into text description like ALFWORLD has. I think it may be a feasible plan if difficult to adapt.

Thanks so much if you can take time to reply!

**Comment by MarcCote** [comment]
Hi @shengyin1224, the text descriptions are generated from the PDDL files, not the AI2THOR's images. So, in order to use ALFWorld, you would need to update the [alfred.pddl](https://github.com/alfworld/alfworld/blob/master/alfworld/data/alfred.pddl) to include your new actions: dirty and break, then update the ALFWorld's [alfred.twl2](https://github.com/alfworld/alfworld/blob/master/alfworld/data/alfred.twl2) grammar file accordingly. Once that's done, you will need to update the problem files (found in the downloaded data, e.g. `~/.cache/alfworld/json_2.1.1/train/look_at_obj_in_light-BasketBall-None-DeskLamp-314/trial_T20190907_142504_035718/initial_state.pddl`) to 1) add the relevant predicates required by your new actions and 2) the goal for that game.

**Comment by shengyin1224** [comment]
Thank you very much @MarcCote! I am also curious that if the version of AI2THOR influence the modification because ALFWORLD use version 2.1.0 but the newest version is 5.0.0.

**Comment by khm159** [comment]
Hello, thank you for your excellent work!

I have a question related to this issue. Since I'm not very familiar with PDDL or game development, I would like to know where to start if I only want to modify the goal condition. I want to keep the same scenes and initial state but change the goal condition.

Thank you once again!

**Comment by MarcCote** [comment]
Hi @shengyin1224 , I do believe it will change the corresponding .pddl file. @MohitShridhar would know more about this. Also, the codebase won't work with a more recent version of AI2THOR, it will just hang (at least that's what people reported to me).

**Comment by shengyin1224** [comment]
ok，thanks very much!
